services:
    mopa.form.help_txt_extension:
           class: Mopa\BootstrapBundle\Form\Extension\HelpFieldTypeExtension
           tags:
                - { name: form.type_extension, alias: field } # the alias is the same than getExtendedType in the class